name: Setup pnpm 📦 and get node_modules dependencies 📥
description: Setups pnpm, installs dependencies and caches them for future runs 🚀
runs:
  using: "composite"
  steps:
    - name: Setup pnpm 📦
      uses: pnpm/action-setup@v3.0.0

    - name: Check if node_modules is cached 📁
      uses: actions/cache@v4
      id: cache-primes
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install dependencies 📥
      if: steps.cache-primes.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm install
